mainSections: ["posts"]

enableEmoji: true
enableGitInfo: true
sidebar:
  emoji: "ðŸ¤˜"
  subtitle: "A blog about software development, support, technology, and other stuff."
  avatar:
    src: "/img/avatar.png"
    alt: "Lecaros"
widgets:
  homepage:
    - type: "categories"
      params:
        title: "Categories"